name: yifu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - click
  - cython
  - dill
  - fasteners
  - networkx
  - numcodecs
  - pathos
  - pox
  - ppft
  - simpleitk
  - numpy>=1.24,<3
  - scipy>=1.13
  - pandas
  - pydantic>=2.0
  - openpyxl
  - napari
  - scikit-image
  - scikit-learn
  - matplotlib
  - dask
  - distributed
  - dask-image
  - dask-jobqueue
  - zarr<3
  - bokeh
  - pyyaml
  - pyqt
  - pyqtgraph
  - tqdm
  - pip:
      - antspyx
      - cellpose
      - torch
      - torchvision
      - opencv-python-headless
      - tifffile
      - fastremap
      - roifile
      - fill-voids
      - natsort
      - nibabel
      - kimimaro
      - connected-components-3d
      - dijkstra3d
      - edt
      - osteoid
      - xs3d
      - crackle-codec
      - google-crc32c
      - microviewer
      - pybind11
